import { Item } from "../data/Item";
/**
 * Interface for the item repository.
 * Introduce the basic CRUD operations on the item table
 */
export abstract class IItemRepository {
    /**
     * Check if an item exists
     * @param id id of the item
     * @returns true if the item exists, otherwise false
     */
    abstract exists(id: number): Promise<boolean>;
    /**
     * Get the item from its id
     * @param id id of the item
     * @returns the item if found, otherwise null
     */
    abstract get(id: number): Promise<Item | null>;
    /**
     * Insert a new item inside the database
     * @param item the entire item
     * @returns the inserted item; of use if one's in need of the id generated by the query
     */
    abstract insert(item: Item): Promise<Item>;
    /**
     * Update an existing item in the database
     * @param item the entire item
     * @returns the updated item if found, otherwise null
     */
    abstract update(item: Item): Promise<Item | null>;
    /**
     * Update an item in the database if it exists, otherwise insert it
     * @param item the entire item
     * @returns the upserted item
     */
    abstract upsert(item: Item): Promise<Item>;
    /**
     * Delete an item from the database
     * @param id id of the item
     */
    abstract delete(id: number): Promise<void>;
}